spring:
  application:
    name: Q-Order
  datasource:
    url: jdbc:mysql://192.168.3.18:3306/jweb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    password: mysqlhxf123456
    username: mysqlhxf
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9082
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.18:9080/eureka