spring:
  application:
    name: Q-Main-Gateway
server:
  port: 9085
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.18:9080/eureka
zuul:
  routes:
    first:
      path: /deal/**
      stripPrefix: false
      serviceId: Q-Rest
    second:
      path: /deal/buy/**
      stripPrefix: false
      serviceId: Q-Rest
    openfile:
      path: /fileSys/**
      serviceId: Open-File
ribbon:
  connectTimeout: 3000
  readTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes,filters